# Generated by Django 4.2 on 2024-09-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=120, unique=True, verbose_name='Title'),
        ),
    ]
