# Generated by Django 4.2 on 2024-09-15 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_alter_article_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='article_covers/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.JSONField(default=dict),
        ),
    ]
