# Generated by Django 4.2 on 2024-09-16 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_remove_article_cover_article_cover_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleV2',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120, unique=True, verbose_name='Title')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cover_name', models.ImageField(null=True, upload_to='cover_image')),
                ('content', models.JSONField(default=dict)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.category')),
                ('tags', models.ManyToManyField(to='article.tag')),
            ],
        ),
    ]
