# Generated by Django 4.2 on 2024-09-16 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_articlev2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlev2',
            old_name='cover_name',
            new_name='cover',
        ),
    ]
