# Generated by Django 4.2 on 2024-09-20 14:52

from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_alter_articlev2_cover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlev2',
            options={'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': '作者', 'verbose_name_plural': '作者'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '分類', 'verbose_name_plural': '分類'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '標籤', 'verbose_name_plural': '標籤'},
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=mdeditor.fields.MDTextField(),
        ),
        migrations.AlterField(
            model_name='articlev2',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.author', verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='articlev2',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.category', verbose_name='分類'),
        ),
        migrations.AlterField(
            model_name='articlev2',
            name='content',
            field=models.JSONField(default=dict, verbose_name='內容'),
        ),
        migrations.AlterField(
            model_name='articlev2',
            name='cover',
            field=models.ImageField(null=True, upload_to='static/images/cover_image', verbose_name='封面'),
        ),
        migrations.AlterField(
            model_name='articlev2',
            name='tags',
            field=models.ManyToManyField(to='article.tag', verbose_name='標籤'),
        ),
        migrations.AlterField(
            model_name='articlev2',
            name='title',
            field=models.CharField(max_length=120, unique=True, verbose_name='標題'),
        ),
    ]
