# Generated by Django 4.2 on 2024-09-22 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
